sudo: false
os:
  - linux
language: node_js
node_js:
  - "4"
  - "5"
before_script:
  - sh -e /etc/init.d/xvfb start
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - TEST_SUITE=unit:node
matrix:
  include:
    - node_js: "4"
      env: TEST_SUITE=lint
    - node_js: "4"
      env: TEST_SUITE=unit:browser
script: npm run $TEST_SUITE
